In [1]:
import numpy as np 


In [13]:
# creating arrays
n_array = np.array([
    [1,4,5,5],
    [2, 4,6, 6]
])
new_array = np.arange(0, 9)
empty = np.empty((2,2))
repeat = np.repeat([1,3,4], 2)

print(n_array, end="\n")
print()
print(new_array,end="\n")
print()
print(empty, end="\n")
print()
print(repeat)

[[1 4 5 5]
 [2 4 6 6]]

[0 1 2 3 4 5 6 7 8]

[[8.48798316e-314 1.06099790e-313]
 [8.48798316e-314 1.27319747e-313]]

[1 1 3 3 4 4]
